# SpringBoot Name
spring.application.name=agg

# Configuration on develop envieronment for PostgreSQL DataBase
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/animalgallerygo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# Default Server Port
server.port=${PORT:8080}

# JPA and Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

